# Use the official image as a parent image
FROM mysql:8.0

# Make port 3306 available to the world outside this container
EXPOSE 3306

# Define environment variables
ENV MYSQL_DATABASE=employee
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password
ENV MYSQL_ROOT_PASSWORD=password
